apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  labels:
    app: fastapi
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        ports:
        - name: http
          containerPort: 8000
        image: ghcr.io/hakoneriksson/fastapi:latest
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi
  labels:
    run: fastapi
spec:
  ports:
  - name: fastapi
    port: 8000
    protocol: TCP
    targetport: http
  selector:
    run: fastapi
  type: LoadBalancer
