---
name: CI

on:
  push: 
    branches:
      - main

jobs:
  build:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push Docker image in api folder
      run: |
        docker build -t ghcr.io/${{ github.repository }}/fastapi:latest ./api
        docker push ghcr.io/${{ github.repository }}/fastapi:latest
